spring:
  datasource:
    url : jdbc:mysql://${MYSQL_HOST:localhost}:3306/institute_crm
    username: root
    password : ICET@1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
